{
 "title": "Hystrix Dashboard",
 "description": "Dashboard to monitor key metrics for Hystrix. The Hystrix metrics are published using Prometheus' simpleclient through this library https://github.com/soundcloud/prometheus-hystrix",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "label_values(job)" },
   { "name": "group", "label": "Group", "query": "label_values(group)" },
   { "name": "function", "label": "function", "query": "label_values(key)" }
  ]
 },
 "panels": [
  {
   "title": "Overall Status",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hystrix_circuit_breaker_open{group=~\"$group\", job=~\"$service\"}) == bool 0 and sum(hystrix_execution_total{event=\"exception_thrown\",group=~\"$group\",job=~\"$service\"}) == bool 0"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(hystrix_execution_total{event=\"failure\",group=~\"$group\",job=~\"$service\"}) + sum(hystrix_execution_total{event=\"short_circuited\",group=~\"$group\",job=~\"$service\"})) / sum(hystrix_execution_terminal_total{group=~\"$group\",job=~\"$service\"}) * 100"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(hystrix_latency_total_seconds_bucket[1m])) by (le)",
     "legendFormat": "{(le)}"
    }
   ]
  },
  {
   "title": "Open Circuit Breakers Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_circuit_breaker_open{group=~\"$group\",job=~\"$service\", key=~\"$function\"}",
     "legendFormat": "{{job}}-{{group}} ({{key}}) "
    }
   ]
  },
  {
   "title": "Command Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_execution_total{event=\"failure\",group=~\"$group\",key=~\"$function\",job=~\"$service\"}",
     "legendFormat": "{{job}}-{{group}} ({{key}}) "
    }
   ]
  },
  {
   "title": "Command Successes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_execution_total{event=\"success\",group=~\"$group\",key=~\"$function\",job=~\"$service\"}",
     "legendFormat": "{{command_name}} ({{command_group}})"
    }
   ]
  },
  {
   "title": "Command Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_execution_total{event=\"timeout\",group=~\"$group\",key=~\"$function\",job=~\"$service\"}",
     "legendFormat": "{{job}}-{{group}} ({{key}}) "
    }
   ]
  },
  {
   "title": "Fallback Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_execution_total{event=\"fallback_success\",group=~\"$group\",key=~\"$function\", job=~\"$service\"}",
     "legendFormat": "{{job}}-{{group}} ({{key}}) "
    }
   ]
  },
  {
   "title": "Fallback Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_execution_total{event=\"fallback_failure\",group=~\"$group\",key=~\"$function\", job=~\"$service\"}",
     "legendFormat": "{{job}}-{{group}} ({{key}}) "
    }
   ]
  },
  {
   "title": "Response from Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_execution_total{event=\"response_from_cache\",group=~\"$group\",key=~\"$function\", job=~\"$service\"}",
     "legendFormat": "{{job}}-{{group}} ({{key}}) "
    }
   ]
  },
  {
   "title": "Thread Pool / Rejected Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hystrix_execution_total{event=\"thread_pool_rejected\",group=~\"$group\",key=~\"$function\", job=~\"$service\"}",
     "legendFormat": "{{job}}-{{group}} ({{key}}) "
    }
   ]
  }
 ]
}