/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.packtpub.mmj.booking.domain.valueobject.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class BookingOrder extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -730048733706875793L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BookingOrder\",\"namespace\":\"com.packtpub.mmj.booking.domain.valueobject.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"restaurantId\",\"type\":\"string\"},{\"name\":\"tableId\",\"type\":\"string\"},{\"name\":\"date\",\"type\":[\"null\",\"string\"]},{\"name\":\"time\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BookingOrder> ENCODER =
      new BinaryMessageEncoder<BookingOrder>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BookingOrder> DECODER =
      new BinaryMessageDecoder<BookingOrder>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<BookingOrder> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<BookingOrder> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BookingOrder>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this BookingOrder to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a BookingOrder from a ByteBuffer. */
  public static BookingOrder fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence userId;
  @Deprecated public java.lang.CharSequence restaurantId;
  @Deprecated public java.lang.CharSequence tableId;
  @Deprecated public java.lang.CharSequence date;
  @Deprecated public java.lang.CharSequence time;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BookingOrder() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param userId The new value for userId
   * @param restaurantId The new value for restaurantId
   * @param tableId The new value for tableId
   * @param date The new value for date
   * @param time The new value for time
   */
  public BookingOrder(java.lang.CharSequence id, java.lang.CharSequence name, java.lang.CharSequence userId, java.lang.CharSequence restaurantId, java.lang.CharSequence tableId, java.lang.CharSequence date, java.lang.CharSequence time) {
    this.id = id;
    this.name = name;
    this.userId = userId;
    this.restaurantId = restaurantId;
    this.tableId = tableId;
    this.date = date;
    this.time = time;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return userId;
    case 3: return restaurantId;
    case 4: return tableId;
    case 5: return date;
    case 6: return time;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: userId = (java.lang.CharSequence)value$; break;
    case 3: restaurantId = (java.lang.CharSequence)value$; break;
    case 4: tableId = (java.lang.CharSequence)value$; break;
    case 5: date = (java.lang.CharSequence)value$; break;
    case 6: time = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'restaurantId' field.
   * @return The value of the 'restaurantId' field.
   */
  public java.lang.CharSequence getRestaurantId() {
    return restaurantId;
  }

  /**
   * Sets the value of the 'restaurantId' field.
   * @param value the value to set.
   */
  public void setRestaurantId(java.lang.CharSequence value) {
    this.restaurantId = value;
  }

  /**
   * Gets the value of the 'tableId' field.
   * @return The value of the 'tableId' field.
   */
  public java.lang.CharSequence getTableId() {
    return tableId;
  }

  /**
   * Sets the value of the 'tableId' field.
   * @param value the value to set.
   */
  public void setTableId(java.lang.CharSequence value) {
    this.tableId = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.lang.CharSequence getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.CharSequence value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'time' field.
   * @return The value of the 'time' field.
   */
  public java.lang.CharSequence getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * @param value the value to set.
   */
  public void setTime(java.lang.CharSequence value) {
    this.time = value;
  }

  /**
   * Creates a new BookingOrder RecordBuilder.
   * @return A new BookingOrder RecordBuilder
   */
  public static com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder newBuilder() {
    return new com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder();
  }

  /**
   * Creates a new BookingOrder RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BookingOrder RecordBuilder
   */
  public static com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder newBuilder(com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder other) {
    return new com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder(other);
  }

  /**
   * Creates a new BookingOrder RecordBuilder by copying an existing BookingOrder instance.
   * @param other The existing instance to copy.
   * @return A new BookingOrder RecordBuilder
   */
  public static com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder newBuilder(com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder other) {
    return new com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder(other);
  }

  /**
   * RecordBuilder for BookingOrder instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BookingOrder>
    implements org.apache.avro.data.RecordBuilder<BookingOrder> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence name;
    private java.lang.CharSequence userId;
    private java.lang.CharSequence restaurantId;
    private java.lang.CharSequence tableId;
    private java.lang.CharSequence date;
    private java.lang.CharSequence time;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userId)) {
        this.userId = data().deepCopy(fields()[2].schema(), other.userId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.restaurantId)) {
        this.restaurantId = data().deepCopy(fields()[3].schema(), other.restaurantId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.tableId)) {
        this.tableId = data().deepCopy(fields()[4].schema(), other.tableId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.date)) {
        this.date = data().deepCopy(fields()[5].schema(), other.date);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.time)) {
        this.time = data().deepCopy(fields()[6].schema(), other.time);
        fieldSetFlags()[6] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing BookingOrder instance
     * @param other The existing instance to copy.
     */
    private Builder(com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userId)) {
        this.userId = data().deepCopy(fields()[2].schema(), other.userId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.restaurantId)) {
        this.restaurantId = data().deepCopy(fields()[3].schema(), other.restaurantId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.tableId)) {
        this.tableId = data().deepCopy(fields()[4].schema(), other.tableId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.date)) {
        this.date = data().deepCopy(fields()[5].schema(), other.date);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.time)) {
        this.time = data().deepCopy(fields()[6].schema(), other.time);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return userId;
    }

    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.userId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'restaurantId' field.
      * @return The value.
      */
    public java.lang.CharSequence getRestaurantId() {
      return restaurantId;
    }

    /**
      * Sets the value of the 'restaurantId' field.
      * @param value The value of 'restaurantId'.
      * @return This builder.
      */
    public com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder setRestaurantId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.restaurantId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'restaurantId' field has been set.
      * @return True if the 'restaurantId' field has been set, false otherwise.
      */
    public boolean hasRestaurantId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'restaurantId' field.
      * @return This builder.
      */
    public com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder clearRestaurantId() {
      restaurantId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'tableId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTableId() {
      return tableId;
    }

    /**
      * Sets the value of the 'tableId' field.
      * @param value The value of 'tableId'.
      * @return This builder.
      */
    public com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder setTableId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.tableId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'tableId' field has been set.
      * @return True if the 'tableId' field has been set, false otherwise.
      */
    public boolean hasTableId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'tableId' field.
      * @return This builder.
      */
    public com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder clearTableId() {
      tableId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.lang.CharSequence getDate() {
      return date;
    }

    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder setDate(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.date = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder clearDate() {
      date = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'time' field.
      * @return The value.
      */
    public java.lang.CharSequence getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * @param value The value of 'time'.
      * @return This builder.
      */
    public com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder setTime(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.time = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'time' field.
      * @return This builder.
      */
    public com.packtpub.mmj.booking.domain.valueobject.avro.BookingOrder.Builder clearTime() {
      time = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BookingOrder build() {
      try {
        BookingOrder record = new BookingOrder();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.userId = fieldSetFlags()[2] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.restaurantId = fieldSetFlags()[3] ? this.restaurantId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.tableId = fieldSetFlags()[4] ? this.tableId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.date = fieldSetFlags()[5] ? this.date : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.time = fieldSetFlags()[6] ? this.time : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BookingOrder>
    WRITER$ = (org.apache.avro.io.DatumWriter<BookingOrder>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BookingOrder>
    READER$ = (org.apache.avro.io.DatumReader<BookingOrder>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
